### ISSUE TITLE
Event mismatches and weird sounds

### ISSUE THREAD

**Issue by wolf6542** [nobowned/rtcwPub#2]
Unknown event 61:
Happens only on maps with trigger multiples so far, like the one attached. Just load it and jump off the edge to reproduce it /couldn't upload the pk3, so had to zip it/.
[ap_rdk-28.zip](https://github.com/nobowned/rtcwPub/files/4195072/ap_rdk-28.zip)
Occurs between newly compiled Wolf SE client and LCSDM/Eascoast, AOD, etc.
Occurs between newly compiled Wolf SE client and newly compiled server.
Doesn't occur between newly compiled Wolf SE client and Nate's rtcwPub.

When using the knife on any surface, it produces the wrong sound:
Occurs on any map.
Occurs between newly compiled Wolf SE client and W@R, AOD, Eastcoast /no sound instead/ etc.
Occurs between newly compiled Wolf SE client and newly compiled server.
Doesn't occur between newly compiled Wolf SE client and Nate's rtcwPub.

**Comment by nobowned** [comment]
Fixed with commit d2337b1ea6c93513e28d1d10911d349af0616e24
